// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: egg.proto

package server

import (
	"context"

	"CCMO/gozero/blog/application/egg/rpc/egg"
	"CCMO/gozero/blog/application/egg/rpc/internal/logic"
	"CCMO/gozero/blog/application/egg/rpc/internal/svc"
)

type EggServer struct {
	svcCtx *svc.ServiceContext
	egg.UnimplementedEggServer
}

func NewEggServer(svcCtx *svc.ServiceContext) *EggServer {
	return &EggServer{
		svcCtx: svcCtx,
	}
}

func (s *EggServer) Comment(ctx context.Context, in *egg.EggRequest) (*egg.EggResponse, error) {
	l := logic.NewCommentLogic(ctx, s.svcCtx)
	return l.Comment(in)
}
